### PR TITLE
Swap J and K behavior

### PR DESCRIPTION
**Pull request by keith**
Following how vim works `J` should go down while `K` goes up.

I get if you don't want to change this since existing users might have an issue with it, but after installing this plugin I was surprised that these seemed to work 'backwards' from what I expected. This would also match the direction you scroll buffers with `j` and `k`. No worries either way.

### CODE REVIEW

**Comment by GermainZ** [comment]
The problem is that up and down depend on where your hotlist bar is, or if you're using an extra plugin and where that plugin's bar is. See #15 for some more info.

**Comment by keith** [comment]
Ah interesting. I suppose my use of buffers.pl is causing this then. Thanks for the explanation. I'll keep an eye on https://github.com/GermainZ/weechat-vimode/issues/20 in the meantime.

**Comment by GermainZ** [comment]
An option could be provided to flip J and K, but auto detection is out of the question. Does that sound good?

**Comment by keith** [comment]
Yea, that would be reasonable. I'm not sure that's worth the time depending on the eta of mappable commands though.

**Comment by GermainZ** [comment]
As of 6c881f0f060a8a2dbb8135d5f1d6db70ca91dda3, this is now possible by executing the following commands while in Normal mode:

```
:nmap J K
:nmap K J
```

**Pull request closed without merging**
